### PR TITLE
Update Cost Management doc links

### PR DESCRIPTION
**Pull request by dlabrecq**
Updated Cost Management links now that the new getting started docs have been published.

https://issues.redhat.com/browse/COST-1562

### CODE REVIEW

**Review by ddonahue007 — APPROVED** [review]
LGTM

**Comment by Hyperkid123** [comment]
@dlabrecq which environments are we targetting here?

**Review by rvsia — APPROVED** [review]

**Comment by dlabrecq** [comment]
@Hyperkid123 These changes would apply to all envs since the doc changes are now live.

**Comment by rvsia** [comment]
@dlabrecq I pushed the changes to stage and prod ENVs.

**Pull request merged**
