### PR TITLE
fix: require permissions for create integration

### PR DESCRIPTION
**Pull request by CodyWMitchell**
### Description

Conditionally display items in the dropdown based on the users permissions.
- If the user has `sources::write` or `sources:*:write` permissions, display both types of integrations and the option to add cloud integrations.
- If the user has `integrations::write`, `integrations:*:write`, or `integrations:endpoints:write` permissions, display both types of integrations and the option to add 3rd-party integrations.
- If user has neither sets of permissions, then the dropdown is disabled.

[RHCLOUD-36321](https://issues.redhat.com/browse/RHCLOUD-36321)

---

#### Both
image

#### Only sources permissions
image

#### Only integrations permissions
image

#### Neither permissions
image

---

### Checklist ☑️
- [X] PR only fixes one issue or story 
- [X] Change reviewed for extraneous code 
- [X] UI best practices adhered to 
- [X] Commits squashed and meaningfully named 
- [X] All PR checks pass locally (build, lint, test, E2E)

##
- [ ] _(Optional) QE: Needs QE attention (OUIA changed, perceived impact to tests, no test coverage)_
- [ ] _(Optional) QE: Has been mentioned_
- [ ] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [ ] _(Optional) UX: Has been mentioned_
##

### CODE REVIEW

**Comment by fhlavac** [comment]
@CodyWMitchell the code looks good. Just the ticket is more about disabling the options in the integration wizard, isn't it?

**Review by fhlavac — APPROVED** [review]

**Comment by fhlavac** [comment]
@CodyWMitchell just curious, does it also cover creating the integration from the empty state in a scenario when the user has only read permissions?

image

**Comment by CodyWMitchell** [comment]
image
image
image

@fhlavac Good catch! Now the tiles in the empty state should also being showing conditionally based on the permissions.

**Review by karelhala — APPROVED** [review]

**Review by fhlavac — APPROVED** [review]

**Pull request merged**
