### PR TITLE
Fix role arn command

### PR DESCRIPTION
**Pull request by adiabramovitch**
Fixing the role arn command to remove " from the ROLE_ARN variable

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@adiabramovitch si this change required for production or just stage?

cc @fhlavac

**Comment by adiabramovitch** [comment]
> @adiabramovitch si this change required for production or just stage?
> 
> 
> 
> cc @fhlavac 

For production as well

**Comment by Hyperkid123** [comment]
@fhlavac can you make sure this gets to prod?

**Comment by fhlavac** [comment]
@Hyperkid123 sure

**Pull request merged**
