### PR TITLE
Use react-query for bit tidier code

### PR DESCRIPTION
**Pull request by ezr-ondrej**
React query seems quite tidier to me, so I guess it makes sense to use it.
Happy to hear if I'm missing something and we can't actually use it :)

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I'll fix tests if we decide to use this :)

**Comment by Hyperkid123** [comment]
@ezr-ondrej we need to have a bit more discussions about it. Sources APi uses graphql and there are also axios-based REST clients.

I don't have anything against react-query as such but I don't want to have another data-fetching library in the project. If we want to migrate towards it then we should do the whole app and remove the other libs.

**Comment by ezr-ondrej** [comment]
> If we want to migrate towards it then we should do the whole app and remove the other libs.

Agreed, I guess it stems from ease of use of react-query, I chose to add it, but I guess I could just learn how to use graphQL for my needs in https://github.com/RedHatInsights/sources-ui/pull/1030#discussion_r1108322935

Happy to have a discussion and help with the move to react-query if we decide to do so, or just close this one out :)

**Comment by Hyperkid123** [comment]
As I said, I have nothing against react query I do quite like it, but it's not going to be a trivial migration. We need some planning discussion if it is even worth it atm.

**Comment by ezr-ondrej** [comment]
Happy to help doing so if we ever decide to do it tho :)

**Pull request closed without merging**
