### PR TITLE
Show "Waiting for update" when check in progress

### PR DESCRIPTION
**Pull request by fhlavac**
This should address https://issues.redhat.com/browse/RHCLOUD-21154

Replaced "Not checked yet" message with "Waiting for update" by default

### CODE REVIEW

**Comment by lindgrenj6** [comment]
So for this one - I think we want to just change the text from "not checked yet" to "waiting for update" when they press the button, that way the UI has some feedback rather than no text changing. 

The end-users don't quite understand it's an async process, so when the UI doesn't change they don't think anything is happening.

**Comment by fhlavac** [comment]
@lindgrenj6 yeah, that's what we should be doing now - when there is no `source.last_checked_at` and no `source.last_available_at` timestamp, we display the "waiting for update" instead of "not checked yet"

**Review by epwinchell — APPROVED** [review]

**Comment by lindgrenj6** [comment]
Yes - I like that change, the other part of it though is like physically changing the text to "waiting for update" after clicking.

like this:

https://user-images.githubusercontent.com/5856504/198078996-571e8467-3f8d-4fe1-b509-07359d01f2e2.mp4

**Comment by fhlavac** [comment]
@lindgrenj6 sure thing, I'll add it

**Comment by lindgrenj6** [comment]
Yes, that's perfectly fine. The initial issue was the the user was confused and thought the button did nothing even though it very much did.

**Comment by fhlavac** [comment]
@lindgrenj6 Ok I'll add it in a bit!

**Comment by fhlavac** [comment]
@lindgrenj6 after a click, the user will now see "Waiting for update" until he refreshes the page. The status pending flag is stored in the application state

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
