### PR TITLE
Refresh table after removal of source after its creation in wizard

### PR DESCRIPTION
**Pull request by rvsia**
The table is now refreshed when users remove a source in Add Source wizard

### CODE REVIEW

**Comment by rvsia** [comment]
@karelhala Can you please review it as MM is not here? :rose:

**Comment by karelhala** [comment]
@rvsia I don't have merge rights so my tick is not gonne be green :disappointed:

**Comment by rvsia** [comment]
@karelhala Thank you!

**Comment by gmcculloug** [comment]
@lgalis If you can review/approval I can merge.

**Pull request merged**
